# Generated by Django 3.2.5 on 2021-08-03 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realisation',
            old_name='photo_befor',
            new_name='photo_before',
        ),
    ]
