# Generated by Django 3.2.5 on 2021-11-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0002_rename_photo_befor_realisation_photo_before'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisation',
            name='photo_after',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='realisation',
            name='photo_before',
            field=models.FileField(upload_to=''),
        ),
    ]
