# Generated by Django 3.2.5 on 2021-11-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0003_auto_20211101_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisation',
            name='photo_after',
            field=models.ImageField(upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='realisation',
            name='photo_before',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
